import pytest
from core.blockchain import ESGBlockchain
from agents.graph import esg_graph

def test_blockchain_integrity():
    bc = ESGBlockchain()
    bc.add_audit_record("test-1", "Test Co", 95.0, "Excellent performance")
    bc.add_audit_record("test-2", "Test Co", 80.0, "Good performance")
    
    assert len(bc.chain) == 3 # Genesis + 2 records
    assert bc.verify_chain() is True

def test_graph_execution():
    initial_state = {
        "company_name": "EcoLogic_Corp",
        "claims": ["Net Zero by 2030"],
        "evidence_found": [],
        "truth_score": 0.0,
        "audit_summary": "",
        "status": "started",
        "messages": []
    }
    
    # This requires mock data to exist (generated by data/generate_mock_data.py)
    result = esg_graph.invoke(initial_state)
    
    assert result["status"] == "complete"
    assert result["truth_score"] >= 0
    assert "Verification successful" in result["audit_summary"]
